### ISSUE TITLE
ValueError: Cannot set tensor: Got value of type INT64 but expected type FLOAT32 for input 0, name: images 

### ISSUE THREAD

**Issue by edumotya** [beasteers/tflit#1]
I get ValueError If the model.dtype is different from any of the inputs dtype. I think it happens because of this line, which assumes that the model.dtype is equal to the inputs dtype:

https://github.com/beasteers/tflit/blob/f766db6a38253b3967daba258f50b04519dc5f53/tflit/core.py#L58

**Comment by beasteers** [comment]
Ah that's a good catch thank you! You're right, we should be doing something like:

```python
    def predict_batch(self, X, multi_input=None, multi_output=None, add_batch=False):
        '''Predict a single batch.'''
        # set inputs
        X = self._check_inputs(X, multi_input)
        input_dtypes = self.input_dtypes
        for i, idx in self._input_idxs:
            x = np.asarray(X[i], dtype=input_dtypes[i])
```
that's actually a general bug with `self.dtype` because it's not a predictable order since it's using a set so that should be fixed too while we're at it.

**Comment by beasteers** [comment]
So I pushed up that change plus some other changes that had been sitting on my local machine.

Another reason could be that your model is expecting floats (which is commonly the case) but you're providing ints, so in that case, you'd do `x.astype(np.float32)` to your numpy array before passing it to the model.

**Comment by edumotya** [comment]
Thank you @beasteers. It worked!
